# Generated by Django 4.2.8 on 2023-12-12 03:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="performance",
            field=models.ForeignKey(
                blank=True,
                default=django.db.models.query.QuerySet.create,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tickets",
                to="theatre.performance",
            ),
        ),
    ]
